// avatar.js - environments, Seed Being render, level-up
// Part of the YOU app. Loaded via index.html in dependency order.

var ENV_STYLES={SEED:"background:radial-gradient(ellipse at 50% 80%, #1a2a0a 0%, #0d0a07 100%)",EMBER:"background:radial-gradient(ellipse at 50% 80%, #2a1005 0%, #0d0a07 100%)",WANDER:"background:radial-gradient(ellipse at 50% 60%, #0a1a0a 0%, #050d0d 100%)",SEEKER:"background:radial-gradient(ellipse at 50% 40%, #050a14 0%, #070505 100%)",ALCH:"background:radial-gradient(ellipse at 50% 50%, #140a02 0%, #050005 100%)",SAGE:"background:radial-gradient(ellipse at 50% 70%, #0a1405 0%, #040804 100%)",ORACLE:"background:radial-gradient(ellipse at 50% 50%, #050010 0%, #000005 100%)",ELDER:"background:radial-gradient(ellipse at 50% 50%, #140a00 0%, #000000 100%)"};
var ENV_MOOD_TINT={NM:"rgba(20,10,30,0.3)",WC:"rgba(10,10,20,0.2)",FQ:"rgba(0,0,0,0)",WG:"rgba(30,20,0,0.1)",FM:"rgba(50,30,0,0.15)"};
function getCurrentStage(){var lv=getLevel(S.totalXP);return LEVELS[lv.level-1]||LEVELS[0];}
function renderAvatar(){var stage=getCurrentStage();var being=document.getElementById("avatarBeing");var env=document.getElementById("avatarEnv");if(!being)return;being.innerHTML='<svg viewBox="0 0 140 180" xmlns="http://www.w3.org/2000/svg">'+AVATAR_SVGS[stage.avatar]+'</svg>';var es=ENV_STYLES[stage.avatar]||ENV_STYLES.SEED;if(selectedMood&&ENV_MOOD_TINT[selectedMood])es+=";box-shadow:inset 0 0 60px "+ENV_MOOD_TINT[selectedMood];env.style.cssText=es;var sn=document.getElementById("avatarStageName");if(sn)sn.textContent=stage.name;var le=document.getElementById("avatarLevel");if(le)le.textContent="Level "+getLevel(S.totalXP).level;}
function checkLevelUp(oldXP,newXP){if(getLevel(newXP).level>getLevel(oldXP).level)triggerLevelUp(getLevel(newXP).level);}
function triggerLevelUp(level){var stage=LEVELS[level-1]||LEVELS[LEVELS.length-1];var ov=document.getElementById("levelUpOverlay");document.getElementById("levelUpTitle").textContent="You have become";document.getElementById("levelUpAvatar").innerHTML='<svg viewBox="0 0 140 180" xmlns="http://www.w3.org/2000/svg">'+AVATAR_SVGS[stage.avatar]+'</svg>';document.getElementById("levelUpName").textContent=stage.name;document.getElementById("levelUpDesc").textContent=stage.desc;ov.classList.add("show");setTimeout(function(){ov.classList.remove("show");},4000);}
