// calendar.js - calendar grid, mood logging
// Part of the YOU app. Loaded via index.html in dependency order.

// ── CALENDAR / MOOD ──
function renderCalendar(){var months=["January","February","March","April","May","June","July","August","September","October","November","December"];document.getElementById("calTitle").textContent=months[calMonth]+" "+calYear;var actDays={},achDays={},compDays={};S.memory.forEach(function(m){var k=m.date_key||m.dateKey;if(k)actDays[k]=(actDays[k]||0)+1;});S.memory.filter(function(m){return !m.name.includes("(check-in)")&&(m.xp||0)>=XP_VALS.habit;}).forEach(function(m){var k=m.date_key||m.dateKey;if(k)achDays[k]=true;});S.memory.filter(function(m){return !m.name.includes("(check-in)")&&(m.xp||0)>=XP_VALS.goal;}).forEach(function(m){var k=m.date_key||m.dateKey;if(k)compDays[k]=true;});var firstDay=new Date(calYear,calMonth,1).getDay();var offset=(firstDay+6)%7;var daysInMonth=new Date(calYear,calMonth+1,0).getDate();var today=getTodayKey();var html="";DAY_LABELS.forEach(function(d){html+="<div class=\"cal-day-label\">"+d+"</div>";});for(var i=0;i<offset;i++)html+="<div class=\"cal-cell empty-cell\"></div>";for(var d=1;d<=daysInMonth;d++){var key=calYear+"-"+String(calMonth+1).padStart(2,"0")+"-"+String(d).padStart(2,"0");var isToday=key===today;var cls=compDays[key]?"has-completion":achDays[key]?"has-achievement":actDays[key]?"has-activity":"";var dot=(actDays[key]||achDays[key]||compDays[key])?"<div class=\"dot\"></div>":"";var seasonLabel="";for(var s=0;s<SEASONAL_EVENTS.length;s++){var ev=SEASONAL_EVENTS[s];if((calMonth+1)===ev.month&&d===ev.day){cls+=(cls?" ":"")+(ev.type==="solstice"?"is-solstice":"is-equinox");seasonLabel="<span class=\"cal-season-label\">"+ev.name.split(" ")[0]+"</span>";break;}}html+="<div class=\"cal-cell"+(isToday?" today":"")+(cls?" "+cls:"")+"\">"+d+dot+seasonLabel+"</div>";}document.getElementById("calGrid").innerHTML=html;renderMoodLog();buildAstroBanner();}
function calNav(dir){calMonth+=dir;if(calMonth>11){calMonth=0;calYear++;}else if(calMonth<0){calMonth=11;calYear--;}renderCalendar();}
function setMood(m,el){selectedMood=m;var btns=document.querySelectorAll(".mood-btn");for(var i=0;i<btns.length;i++)btns[i].classList.remove("selected");if(el)el.classList.add("selected");document.getElementById("moodLabel").textContent=MOOD_LABELS[m]||"";renderAvatar();}
async function logMood(){if(!selectedMood){showToast("Choose a moon phase first");return;}var energy=parseInt(document.getElementById("energySlider").value);var entry={mood:selectedMood,energy:energy,date:new Date().toLocaleDateString("en-AU",{day:"numeric",month:"short",year:"numeric"}),dateKey:getTodayKey()};S.moodLog.unshift(entry);if(S.moodLog.length>90)S.moodLog.pop();renderMoodLog();showToast("+ Energy logged");await saveMood(entry);setSync("synced");}
function renderMoodLog(){var el=document.getElementById("moodLog");if(!S.moodLog.length){el.innerHTML="";return;}el.innerHTML=S.moodLog.slice(0,7).map(function(e){var emoji=MOOD_EMOJI[e.mood]||e.mood;var label=MOOD_LABELS[e.mood]?MOOD_LABELS[e.mood].split(" - ")[0]:"";return "<div class=\"mood-entry\"><span style=\"font-size:16px\">"+emoji+"</span><span style=\"flex:1;font-size:11px;color:var(--cream);opacity:.7\">"+label+"</span><span style=\"color:var(--ember);font-size:11px\">vitality "+e.energy+"/10</span><span class=\"memory-date\">"+e.date+"</span></div>";}).join("");}
