// astrology.util.js - sun/moon/rising, moon phase, guidance
// Part of the YOU app. Loaded via index.html in dependency order.

// ── ASTROLOGY ──
var ZODIAC=[{s:"Capricorn",fm:12,fd:22,tm:1,td:19},{s:"Aquarius",fm:1,fd:20,tm:2,td:18},{s:"Pisces",fm:2,fd:19,tm:3,td:20},{s:"Aries",fm:3,fd:21,tm:4,td:19},{s:"Taurus",fm:4,fd:20,tm:5,td:20},{s:"Gemini",fm:5,fd:21,tm:6,td:20},{s:"Cancer",fm:6,fd:21,tm:7,td:22},{s:"Leo",fm:7,fd:23,tm:8,td:22},{s:"Virgo",fm:8,fd:23,tm:9,td:22},{s:"Libra",fm:9,fd:23,tm:10,td:22},{s:"Scorpio",fm:10,fd:23,tm:11,td:21},{s:"Sagittarius",fm:11,fd:22,tm:12,td:21}];
var SIGN_NAMES=["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
function getSunSign(b){var d=new Date(b);var m=d.getMonth()+1;var day=d.getDate();for(var i=0;i<ZODIAC.length;i++){var z=ZODIAC[i];if((m===z.fm&&day>=z.fd)||(m===z.tm&&day<=z.td))return z.s;}return "Capricorn";}
function getMoonSign(b){var d=new Date(b);var ref=new Date("2000-01-01");var days=Math.floor((d-ref)/86400000);return SIGN_NAMES[Math.abs(Math.floor(days/2.275))%12];}
function getRisingSign(b,t){if(!t)return "Unknown";var d=new Date(b+"T"+t);var ref=new Date("2000-01-01");var days=Math.floor((d-ref)/86400000);var h=d.getHours();return SIGN_NAMES[(Math.abs(Math.floor(days/1.25))+Math.floor(h/2))%12];}
function getMoonPhase(){var d=new Date();var year=d.getFullYear();var month=d.getMonth()+1;var day=d.getDate();if(month<3){year--;month+=12;}var a=Math.floor(year/100);var b=2-a+Math.floor(a/4);var jd=Math.floor(365.25*(year+4716))+Math.floor(30.6001*(month+1))+day+b-1524.5;var dsn=(jd-2451549.5)%29.53058867;if(dsn<0)dsn+=29.53058867;if(dsn<1.85)return {name:"New Moon",emoji:MOOD_EMOJI.NM};if(dsn<7.38)return {name:"Waxing Crescent",emoji:MOOD_EMOJI.WC};if(dsn<9.22)return {name:"First Quarter",emoji:MOOD_EMOJI.FQ};if(dsn<14.77)return {name:"Waxing Gibbous",emoji:MOOD_EMOJI.WG};if(dsn<16.61)return {name:"Full Moon",emoji:MOOD_EMOJI.FM};if(dsn<22.15)return {name:"Waning Gibbous",emoji:"\ud83c\udf16"};if(dsn<23.99)return {name:"Last Quarter",emoji:"\ud83c\udf17"};return {name:"Waning Crescent",emoji:"\ud83c\udf18"};}
function getMoonInSign(){var d=new Date();var ref=new Date("2000-01-01");var days=(d-ref)/86400000;return SIGN_NAMES[Math.abs(Math.floor(days/2.275))%12];}
var PHASE_GUIDANCE={"New Moon":{energy:"Potent stillness. Seeds planted now carry great power.",intention:"Set one clear intention for this lunar cycle. What do you most wish to call in?",watch:"Resist the urge to rush. New moons ask for planting, not harvesting.",week:"The coming week supports new beginnings and quiet reflection. Energy builds slowly."},"Waxing Crescent":{energy:"Early momentum. The seed has broken ground.",intention:"Take one small action toward what you planted at the new moon.",watch:"Doubt may arise as you begin. This is normal. Keep moving.",week:"Growing energy supports taking first steps and building momentum."},"First Quarter":{energy:"Tension that creates. Obstacles are invitations.",intention:"Face the thing that is resisting you. It holds your next breakthrough.",watch:"The pull to give up is strongest here. This discomfort is the work.",week:"This week may feel challenging. Decisions are required. Lean into the friction."},"Waxing Gibbous":{energy:"Refinement and patience. Almost there.",intention:"Review what you have built. What needs adjusting before completion?",watch:"Perfectionism can sabotage nearly-finished things. Done is sacred.",week:"Strong energy for refining and preparing. The full moon approaches."},"Full Moon":{energy:"Peak illumination. What has been hidden comes to light.",intention:"Celebrate what has come to fruition. Release what no longer serves.",watch:"Emotions run high under the full moon. Feel them without being swept away.",week:"Heightened emotional energy and clarity. Powerful for completion and release."},"Waning Gibbous":{energy:"Gratitude and sharing. The harvest continues.",intention:"Share what you have learned or created with someone in your life.",watch:"Avoid holding too tightly to outcomes. The tide is turning inward.",week:"Supportive energy for sharing, teaching, and expressing gratitude."},"Last Quarter":{energy:"Release and forgiveness. Clearing the temple.",intention:"Identify one thing to consciously release before the new moon.",watch:"This is not the time to start new projects. Finish, clear, and close.",week:"The week supports letting go, forgiveness, and clearing space."},"Waning Crescent":{energy:"Deep rest and surrender. The void before renewal.",intention:"Rest without agenda. Let yourself not know what comes next.",watch:"The impulse to fill the silence. Sit in it. Wisdom lives there.",week:"Lowest energy of the cycle. Honour the need to rest and withdraw."}};
var SIGN_ENERGY={Aries:"bold and initiating",Taurus:"grounded and sensual",Gemini:"curious and communicative",Cancer:"intuitive and nurturing",Leo:"radiant and expressive",Virgo:"discerning and precise",Libra:"harmonising and reflective",Scorpio:"deep and transformative",Sagittarius:"expansive and seeking",Capricorn:"purposeful and enduring",Aquarius:"visionary and unconventional",Pisces:"dreamy and compassionate"};
var SIGN_WATCH={Aries:"impulsiveness dressed as courage",Taurus:"stubbornness when flow is being asked for",Gemini:"scattered energy - choose one thread",Cancer:"retreating from what needs to be faced",Leo:"seeking validation rather than giving light",Virgo:"criticism masking deeper feeling",Libra:"people-pleasing at the cost of your truth",Scorpio:"control as a response to vulnerability",Sagittarius:"avoiding the details that need tending",Capricorn:"coldness toward your own emotional needs",Aquarius:"detachment from personal intimacy",Pisces:"escapism when presence is needed"};
function buildAstroBanner(){var phase=getMoonPhase();var moonSign=getMoonInSign();var g=PHASE_GUIDANCE[phase.name]||PHASE_GUIDANCE["New Moon"];var personalLabel="Current Sky";var personalEnergy=g.energy;var personalWatch=g.watch;if(userProfile&&userProfile.sunSign){var sun=userProfile.sunSign;var rising=(userProfile.risingSign&&userProfile.risingSign!=="Unknown")?" / "+userProfile.risingSign:"";personalLabel=sun+rising;personalEnergy=g.energy+" For "+sun+", this amplifies your "+(SIGN_ENERGY[sun]||"natural")+" nature.";personalWatch=g.watch+" As a "+sun+", watch especially for "+(SIGN_WATCH[sun]||"overthinking")+".";}var loading=document.getElementById("astroLoading");var content=document.getElementById("astroContent");if(!loading||!content)return;loading.style.display="none";content.style.display="block";document.getElementById("astroMoon").textContent=phase.emoji;document.getElementById("astroPhase").textContent=phase.name;document.getElementById("astroSign").textContent="Moon in "+moonSign+" - "+new Date().toLocaleDateString("en-AU",{weekday:"long",day:"numeric",month:"long"});document.getElementById("astroPersonal").textContent=personalLabel;document.getElementById("astroEnergy").textContent=personalEnergy;document.getElementById("astroIntention").textContent=g.intention;document.getElementById("astroWatch").textContent=personalWatch;document.getElementById("astroWeek").textContent=g.week;var wr=document.getElementById("astroWeekRow");if(wr)wr.style.display="flex";buildSeasonalBanner();}
function buildSeasonalBanner(){var now=new Date();var m=now.getMonth()+1;var d=now.getDate();var banner=document.getElementById("seasonalBanner");if(!banner)return;var found=null;for(var i=0;i<SEASONAL_EVENTS.length;i++){var ev=SEASONAL_EVENTS[i];var diff=Math.abs((m-ev.month)*30+(d-ev.day));if(diff<=3){found=ev;break;}}if(found){document.getElementById("seasonalTitle").textContent=found.name;document.getElementById("seasonalDesc").textContent=found.desc;banner.classList.add("show");}else{banner.classList.remove("show");}}
