// Compiles The ValYOU's Codex (content/valyous-codex/**.md) into:
//   1. src/constants/codex.generated.js   — what the app reads
//   2. ../supabase/codex/values_library.sql — upsert for the values_library
//      table (paste into the Supabase SQL editor after Codex edits)
//
// The Markdown files are the source of truth. Never edit the outputs by
// hand; edit the Codex and run:  npm run codex
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const CODEX_DIR = join(HERE, "..", "content", "valyous-codex");
const JS_OUT = join(HERE, "..", "src", "constants", "codex.generated.js");
const SQL_DIR = join(HERE, "..", "..", "supabase", "codex");
const SQL_OUT = join(SQL_DIR, "values_library.sql");

const ELEMENT_ORDER = ["Water", "Fire", "Earth", "Air", "Ether"];
const SECTIONS = {
  "Essence": "essence",
  "Light": "light",
  "Shadow (excess)": "shadow",
  "Void (deficiency)": "void",
  "What keeps it whole": "whole"
};

function walk(dir) {
  return readdirSync(dir).flatMap(name => {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) return walk(p);
    return name.endsWith(".md") && !name.startsWith("_") ? [p] : [];
  });
}

function parseFrontmatter(src) {
  const m = src.replace(/^﻿/, "").match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) throw new Error("missing frontmatter");
  const fm = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.replace(/\s+#.*$/, "").match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, raw] = kv;
    const val = raw.trim();
    fm[key] = val.startsWith("[")
      ? val.slice(1, -1).split(",").map(s => s.trim()).filter(Boolean)
      : val;
  }
  return fm;
}

function parseSections(src) {
  const out = {};
  const parts = src.split(/^## /m).slice(1);
  for (const part of parts) {
    const [heading, ...rest] = part.split(/\r?\n/);
    const key = SECTIONS[heading.trim()];
    if (key) out[key] = rest.join("\n").trim();
  }
  const notes = (src.match(/## Questionnaire notes\r?\n([\s\S]*?)(?=\r?\n## |$)/) || [])[1] || "";
  out.questionnaireNotes = notes.split(/\r?\n/).map(l => l.replace(/^-\s*/, "").trim()).filter(Boolean);
  return out;
}

const entries = walk(CODEX_DIR).map(file => {
  const src = readFileSync(file, "utf-8");
  const fm = parseFrontmatter(src);
  const s = parseSections(src);
  if (fm.type !== "main") return null; // sub-values join once their files exist
  for (const k of ["name", "slug", "element"]) if (!fm[k]) throw new Error(`${file}: missing ${k}`);
  return {
    name: fm.name, slug: fm.slug, element: fm.element, status: fm.status || "draft",
    pillars: fm.pillars || [], balancingKin: fm.balancing_kin || [], nourishingKin: fm.nourishing_kin || [],
    synonyms: fm.synonyms || [], subValues: fm.sub_values || [],
    essence: s.essence || "", light: s.light || "", shadow: s.shadow || "", void: s.void || "",
    whole: s.whole || "", questionnaireNotes: s.questionnaireNotes
  };
}).filter(Boolean).sort((a, b) =>
  ELEMENT_ORDER.indexOf(a.element) - ELEMENT_ORDER.indexOf(b.element) || a.name.localeCompare(b.name)
);

// Every kin link must point at a main value that exists.
const slugs = new Set(entries.map(e => e.slug));
const broken = entries.flatMap(e => [...e.balancingKin, ...e.nourishingKin].filter(k => !slugs.has(k)).map(k => `${e.slug} → ${k}`));
if (broken.length) throw new Error("Unknown kin: " + broken.join(", "));

writeFileSync(JS_OUT,
`// GENERATED by scripts/compile-codex.mjs from content/valyous-codex.
// Do not edit by hand — edit the Codex and run \`npm run codex\`.
export const CODEX = ${JSON.stringify(entries, null, 2)};
`);

const q = s => "'" + String(s).replace(/'/g, "''") + "'";
const arr = xs => "'{" + xs.map(x => '"' + x.replace(/"/g, '\\"') + '"').join(",") + "}'";
const rows = entries.map(e =>
  `  (${q(e.slug)}, ${q(e.name)}, ${q(e.element)}, ${q(e.essence)}, ${q(e.light)}, ${q(e.shadow)}, ${q(e.void)}, ` +
  `${arr(e.pillars)}, ${arr(e.balancingKin)}, ${arr(e.nourishingKin)}, ${arr(e.synonyms)})`
);
mkdirSync(SQL_DIR, { recursive: true });
writeFileSync(SQL_OUT,
`-- GENERATED by web-next/scripts/compile-codex.mjs from The ValYOU's Codex.
-- Upserts all ${entries.length} main values into values_library. Safe to re-run
-- after every Codex edit. Run in the Supabase SQL editor for project
-- yikoymzktspamahrsuje. Needs 20260928140000_values_system.sql first.

insert into public.values_library
  (slug, name, element, essence, light, shadow, void, pillars, balancing_kin, nourishing_kin, synonyms)
values
${rows.join(",\n")}
on conflict (slug) do update set
  name = excluded.name, element = excluded.element, essence = excluded.essence,
  light = excluded.light, shadow = excluded.shadow, void = excluded.void,
  pillars = excluded.pillars, balancing_kin = excluded.balancing_kin,
  nourishing_kin = excluded.nourishing_kin, synonyms = excluded.synonyms;
`);

console.log(`Codex compiled: ${entries.length} values → ${JS_OUT} and ${SQL_OUT}`);
